# Generated by Django 2.2 on 2021-05-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(default='', max_length=255),
        ),
    ]
