# Generated by Django 2.2 on 2021-06-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_auto_20210531_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='meet',
            field=models.CharField(default='', max_length=255),
        ),
    ]
