# Generated by Django 2.2 on 2021-06-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0009_auto_20210531_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
