# Generated by Django 2.2 on 2021-06-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0010_auto_20210601_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='message',
            field=models.TextField(),
        ),
    ]
