# Generated by Django 2.2 on 2021-06-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0013_about_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='file',
        ),
    ]
