# Generated by Django 2.2 on 2021-06-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0016_auto_20210611_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='file',
            field=models.FileField(default=None, upload_to='user_images'),
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
