# Generated by Django 2.2 on 2021-06-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0017_auto_20210611_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='file',
            field=models.FileField(default='static/img/default.png', upload_to='user_images'),
        ),
    ]
